export const GOOGLE_WEB_CLIENT_ID = process.env.EXPO_PUBLIC_GOOGLE_CLIENT_ID || '';
export const GOOGLE_IOS_CLIENT_ID = process.env.EXPO_PUBLIC_GOOGLE_IOS_CLIENT_ID || GOOGLE_WEB_CLIENT_ID;
export const GOOGLE_ANDROID_CLIENT_ID = process.env.EXPO_PUBLIC_GOOGLE_ANDROID_CLIENT_ID || GOOGLE_WEB_CLIENT_ID;
export const GOOGLE_PROXY_PROJECT_NAME = process.env.EXPO_PUBLIC_GOOGLE_PROXY_PROJECT_NAME || '';
export const GOOGLE_PROXY_REDIRECT_URI = GOOGLE_PROXY_PROJECT_NAME
	? `https://auth.expo.io/${GOOGLE_PROXY_PROJECT_NAME}`
	: '';
